[unix_http_server]
file=/tmp/supervisor.sock

[supervisord]
nodaemon=true
logfile=/tmp/supervisord.log
pidfile=/tmp/supervisord.pid
childlogdir=/tmp
loglevel=info

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[program:app]
command=/usr/bin/env bash /app/scripts/sh/run_app_supervisor.sh
directory=/app
autostart=true
autorestart=unexpected
startsecs=3
startretries=1000
exitcodes=0
stopsignal=TERM
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
priority=10

[program:listener]
command=/usr/bin/env bash /app/scripts/sh/run_listener_supervisor.sh
directory=/app
autostart=true
autorestart=unexpected
startsecs=3
startretries=1000
exitcodes=0
stopsignal=TERM
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
priority=20

[program:discord]
command=/usr/bin/env bash /app/scripts/sh/run_discord_supervisor.sh
directory=/app
autostart=true
autorestart=unexpected
startsecs=3
startretries=1000
exitcodes=0
stopsignal=TERM
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
priority=30
